name: trigger-docker-builds-test

on:
  workflow_dispatch:

jobs:
  run-tdb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download and unpack GitHub CLI
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            cd /tmp
            curl -o './github-cli.tar.gz' -L 'https://github.com/cli/cli/releases/download/v1.10.0/gh_1.10.0_linux_amd64.tar.gz'
            tar -xvf './github-cli.tar.gz'
            sudo cp ./gh*linux_amd64/bin/gh '/usr/local/bin/'
      - name: Authenticate with GitHub for private Gist
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            echo "${{ secrets.TDB_PAT }}" | gh auth login --with-token
      - name: Get Gist ID
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            config_file='trigger-docker-build-config'
            gist_id=$(gh gist list --secret | grep -P -m 1 "${config_file}" | awk -F ' ' '{ print $1 }')
      - name: Change directory to workspace
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            cd "${GITHUB_WORKSPACE}
      - name: Download config from secret Gist
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            gh gist clone "${gist_id}" '/tmp/gist'
            cp '/tmp/gist/config.ini' './configs'
      - name: Run TDB
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            python2 ./lib/pex/TriggerDockerBuild.pex ./TriggerDockerBuild.py --config ./configs --logs ./logs
      - name: Create Gist
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            gh gist create --filename './configs/config.ini'
      - name: Delete old Gist
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            true
      - name: Debug
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          retry_on: error
          command: |
            pwd
            cat './configs/config.ini'
            export
            ls -al
            ls -al ./configs
            ls -al ./logs